version: '2'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
      
  mysql:
    image: mysql
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: demo
    ports:
      - 3306:3306

  arangodb:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: demo
    ports:
      - 8529:8529


  elasticsearch:
    image: elasticsearch:2
    environment:
     # This helps ES out with memory usage
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    ports:
      - 9200:9200
